theme: jekyll-theme-minimal
title: Corwin Finance
logo: /assets/img/corwin-logo-x128.png
icon: /assets/img/favicon.ico
description: Projects started with Corwin Finance

gitalk:
  clientID: 3d4a378445ce6c4eef4c
  clientSecret: 151367bb137caec661aa9a77ef007465e478f130
  repo: about
  owner: CorwinCheung2023

url: https://about.corwin.com.kg
